#!/bin/bash

FLOOR=
FLOOR=-f
VISPORTALS=-p

rm -f *.pyc
echo -n "txt2pen: converting txt representation into pen map:  "
if PYTHONPATH=student python txt2pen.py -l -f 3 -o tiny.pen $1 ; then
    echo "pass"
else
    echo "failed"
    exit 1
fi

if PYTHONPATH=student python pen2map.py ${VISPORTALS} ${FLOOR} -b -c tiny.ss -s -e -o tiny.map tiny.pen ; then
    echo "pen2map: converting pen map into doom3 map: pass"
else
    echo "pen2map: converting pen map into doom3 map: failed"
    exit 1
fi
