#!/bin/bash

rm *.pyc
echo -n "txt2pen: "
if PYTHONPATH=student python txt2pen.py -l -f 3 -o tiny.pen $1 ; then
    echo "pass"
else
    echo "failed"
    exit 1
fi

if PYTHONPATH=student python pen2map.py -fb -c tiny.ss -s -e -o tiny.map tiny.pen ; then
    echo "pen2map: pass"
else
    echo "pen2map: failed"
    exit 1
fi
