#!/bin/bash

FLOOR=
FLOOR=-f
PORTALS=
PORTALS=-p

rm *.pyc
echo -n "txt2pen: "
if PYTHONPATH=../../solutions python txt2pen.py -l -f 5 -o tiny.pen $1 ; then
    echo "pass"
else
    echo "failed"
    exit 1
fi

if PYTHONPATH=../../solutions python pen2map.py ${PORTALS} -O ${FLOOR} -V -b -s -e -o tiny.map tiny.pen ; then
    echo "pen2map: pass"
else
    echo "pen2map: failed"
    exit 1
fi
